[package]
name = "catalog"
version = "0.3.0"
authors = ["Casper Rogild Storm"]
edition = "2018"

[workspace]
members = [
    ".",
    "crates/core"
]

[dependencies]
core = { path = "crates/core" }
structopt = "0.3.21"
futures = "0.3.15"
serde_json = "1.0.64"
